# Generated by Django 5.0.8 on 2024-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dicom_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.CharField(max_length=100)),
                ('modality', models.CharField(max_length=50)),
                ('series_instance_uid', models.CharField(max_length=100)),
                ('study_instance_uid', models.CharField(max_length=100)),
            ],
        ),
    ]
