# Generated by Django 5.0.8 on 2024-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfile',
            name='doctype',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
